# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_reports}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2009-10-14}
  s.description = %q{This is a plugin for Redmine reports}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "COPYRIGHT.txt",
     "CREDITS.txt",
     "GPL.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/system_reports_controller.rb",
     "app/helpers/system_reports_helper.rb",
     "app/models/activity_report.rb",
     "app/models/completion_count.rb",
     "app/views/settings/_redmine_reports_settings.html.erb",
     "app/views/system_reports/_billing_export.html.erb",
     "app/views/system_reports/_completion_count_for_user.html.erb",
     "app/views/system_reports/_menu.html.erb",
     "app/views/system_reports/activity_report.html.erb",
     "app/views/system_reports/completion_count.html.erb",
     "app/views/system_reports/index.html.erb",
     "app/views/system_reports/quickbooks.html.erb",
     "assets/images/chart_line.png",
     "assets/images/chart_organisation.png",
     "assets/images/house.png",
     "assets/images/user_comment.png",
     "assets/stylesheets/redmine_reports.css",
     "config/locales/en.yml",
     "init.rb",
     "lang/en.yml",
     "lib/ephemeral_model.rb",
     "lib/reports/activity_report.rb",
     "lib/reports/completion_count.rb",
     "lib/reports/quickbooks.rb",
     "lib/reports/report_helper.rb",
     "lib/tasks/plugin_stat.rake",
     "rails/init.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/TODO}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{redmine_reports}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{This is a plugin for Redmine reports}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/models/completion_count_spec.rb",
     "spec/models/activity_report_spec.rb",
     "spec/controllers/system_reports_completion_count_spec.rb",
     "spec/controllers/system_reports_overview_spec.rb",
     "spec/controllers/system_reports_activity_report_spec.rb",
     "spec/controllers/system_reports_quickbooks_spec.rb",
     "spec/sanity_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
